scollet:jnederlo

In [2]:
from numpy import random
random.standard_exponential([1000])

array([  1.28244470e+00,   1.47699144e+00,   3.07968609e-01,
         2.61974422e+00,   4.65301522e-01,   2.36181204e+00,
         5.15619002e-01,   5.49940473e-01,   5.58916046e-01,
         3.88980626e-01,   8.57610961e-01,   4.76875535e-01,
         3.57218736e+00,   1.25271476e-01,   1.59041981e+00,
         1.84129010e+00,   6.83333764e+00,   1.21513232e+00,
         6.72458817e-01,   1.37657669e+00,   8.32540358e-01,
         1.35198566e+00,   1.04668512e+00,   2.21088083e-01,
         6.91162167e-01,   3.21353663e-01,   9.92341151e-02,
         8.53889829e-01,   1.36130125e+00,   6.84691669e-03,
         7.75259508e-01,   1.70951347e+00,   3.19093851e-01,
         1.17986565e+00,   7.86293290e-01,   1.62004291e+00,
         2.72191305e+00,   1.40994832e+00,   1.97690878e+00,
         1.46384529e+00,   5.46550337e-01,   4.39452679e+00,
         6.23577235e-01,   1.30475872e+00,   3.42661835e-01,
         1.17282728e+00,   1.75257135e-01,   4.46667933e-02,
         1.21085086e+00,

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
arr.reshape((4, 3))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [1]:
import numpy as np
from numpy import asarray
def func(n):
    return np.random.choice([0, 1], size=(n,))

asarray(func(5)).shape

(5,)

In [1]:
import numpy as np

np.random.randn(10, 12)[0:4, 8:12]

array([[-0.07711037, -1.44310427, -0.00558982, -0.52427997],
       [-2.62352135,  0.67406832, -1.26416288, -0.36220407],
       [-0.57217694,  0.14523726, -0.71206205, -1.32560259],
       [-0.98694416,  0.32829878, -0.14318046,  1.236558  ]])

In [ ]:
import numpy as np
def get(m)
    np.random.randn(m)
def func(n):
    return np.random.choice([0, 1], size=(n,))

get().concatenate